In [214]:
import numpy as np
import itertools
import re

from operator import itemgetter

with open('input.txt') as f:
    lines = f.readlines()

#lines = [x.strip() for x in lines]
lines = [list(map(int,re.findall(r'\d+',line))) for line in lines]

In [106]:
lines

[[1, 1], [1, 6], [8, 3], [3, 4], [5, 5], [8, 9]]

In [118]:
grid2 = np.zeros((10,10))
for ix,iy in np.ndindex(grid2.shape):
    print(ix,iy)

0 0
0 1
0 2
0 3
0 4
0 5
0 6
0 7
0 8
0 9
1 0
1 1
1 2
1 3
1 4
1 5
1 6
1 7
1 8
1 9
2 0
2 1
2 2
2 3
2 4
2 5
2 6
2 7
2 8
2 9
3 0
3 1
3 2
3 3
3 4
3 5
3 6
3 7
3 8
3 9
4 0
4 1
4 2
4 3
4 4
4 5
4 6
4 7
4 8
4 9
5 0
5 1
5 2
5 3
5 4
5 5
5 6
5 7
5 8
5 9
6 0
6 1
6 2
6 3
6 4
6 5
6 6
6 7
6 8
6 9
7 0
7 1
7 2
7 3
7 4
7 5
7 6
7 7
7 8
7 9
8 0
8 1
8 2
8 3
8 4
8 5
8 6
8 7
8 8
8 9
9 0
9 1
9 2
9 3
9 4
9 5
9 6
9 7
9 8
9 9


In [24]:
list(map(int,re.findall(r'\d+',lines[0])))

[1, 1]

In [215]:
points = {}
for i, p in enumerate(lines,1):
    points[i] = (p[0],p[1])
    # grid[points[i]] = i
maxDim = max(max(points.items(), key=itemgetter(1))[1][1],max(points.items(), key=itemgetter(1))[1][0])
print(maxDim)
grid = np.zeros((maxDim+3,maxDim+3))
print(points)
for k,v in points.items():

    grid[v] = k
#    print(p.value())

numPoints = len(points)
def closestPoint(p,points):
    dists = np.zeros(numPoints)
    for k,v in points.items():
        dists[k-1] = abs(p[0]-v[0]) + abs(p[1]-v[1])
    minDist = min(dists)
    minPoint = np.argmin(dists)
    #print(dists)
    #print(str(minDist)+"@"+str(minPoint+1))
    #print(np.where(dists==minDist)[0])
    if (len(np.where(dists==minDist)[0])==1):
        return int(minPoint + 1)
    else:
        return int(-1)

for ix,iy in np.ndindex(grid.shape):
    grid[(ix,iy)] = closestPoint((ix,iy),points)

print(grid)
    
areas=[]
for k,v in points.items():
    subGrid = np.where(grid==k)

    if np.any(subGrid[0]==0)  or np.any(subGrid[1] == 0) or np.any(subGrid[0]==maxDim+2)  or np.any(subGrid[1] == maxDim+2):
        print(str(k)+" Infite")
    else:
        print(str(k)+":"+ str(len(np.where(grid == k)[0])))
        areas.append(len(np.where(grid == k)[0]))
    
print(max(areas))
grid = np.zeros((maxDim+3,maxDim+3))

for ix,iy in np.ndindex(grid.shape):
    for k,v in points.items():
        grid[(ix,iy)] += abs(ix-v[0]) + abs(iy-v[1])
                           
print(len(np.where(grid<10000)[0]))

359
{1: (137, 282), 2: (229, 214), 3: (289, 292), 4: (249, 305), 5: (90, 289), 6: (259, 316), 7: (134, 103), 8: (96, 219), 9: (92, 308), 10: (269, 59), 11: (141, 132), 12: (71, 200), 13: (337, 350), 14: (40, 256), 15: (236, 105), 16: (314, 219), 17: (295, 332), 18: (114, 217), 19: (43, 202), 20: (160, 164), 21: (245, 303), 22: (339, 277), 23: (310, 316), 24: (164, 44), 25: (196, 335), 26: (228, 345), 27: (41, 49), 28: (84, 298), 29: (43, 51), 30: (158, 347), 31: (121, 51), 32: (176, 187), 33: (213, 120), 34: (174, 133), 35: (259, 263), 36: (210, 205), 37: (303, 233), 38: (265, 98), 39: (359, 332), 40: (186, 340), 41: (132, 99), 42: (174, 153), 43: (206, 142), 44: (341, 162), 45: (180, 166), 46: (152, 249), 47: (221, 118), 48: (95, 227), 49: (152, 186), 50: (72, 330)}
[[27. 27. 27. ... 50. 50. 50.]
 [27. 27. 27. ... 50. 50. 50.]
 [27. 27. 27. ... 50. 50. 50.]
 ...
 [10. 10. 10. ... 39. 39. 39.]
 [10. 10. 10. ... 39. 39. 39.]
 [10. 10. 10. ... 39. 39. 39.]]
1:2978
2:3623
3:1651
4:448
5:1

In [200]:
dd=np.array([3.,2.,3.])
subGrid = np.where(grid==6)
    #print("INF")
if np.any(subGrid[0]==0)  or np.any(subGrid[1] == 0) or np.any(subGrid[0]==maxDim+2)  or np.any(subGrid[1] == maxDim+2):
    print("INFINITY")

INFINITY


In [174]:
print(len(np.where(dd == 3)[0]))

2


In [133]:
if 1.0 in np.unique(dd):
    print("Einziugartig")
#print(type(maxX))
#print(tuple(map(lambda x, y: x + y, maxX, (1,1))))
#np.zeros(maxX)

Einziugartig


In [82]:
max(points.items(), key=itemgetter(1))[1][1]

9

In [36]:

grid[(0,0)] = 99

In [39]:
points[4]

(5, 5)

In [51]:
max(points[6])

9

In [113]:
a = np.array([1,2,3,4,1])

In [114]:
np.argmin(a)

0